jabba/urls.py
import settings
from django.conf.urls.defaults import *
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required


from helpdesk.views import dashboard_user, dashboard_staff, dashboard_team, \
                           task_user_add, task_detail, team, note_add, \
                           attachment_add, task_team_add, task_change_team, \
                           context, task_change_priority, task_close, \
                           task_detail_change_team, task_assign, \
                           task_change_context, index


from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.urls')),
    url(r'^$', index, name='home'),
    url(r'^dashboard/user/$', dashboard_user, name='helpdesk_dashboard_user'),
    url(r'^dashboard/staff/$', dashboard_staff, name='helpdesk_dashboard_staff'),
    url(r'^dashboard/team/(?P<team_id>\d+)/$', dashboard_team, name='helpdesk_dashboard_team'),
    url(r'^task/team/add/$', task_team_add, name='helpdesk_task_team_add'),
    url(r'^task/user/add/$', task_user_add, name='helpdesk_task_user_add'),
    url(r'^task/(?P<task_id>\d+)/detail/$', task_detail, name='helpdesk_task_detail'),
    url(r'^task/(?P<task_id>\d+)/change/team/(?P<team_id>\d+)/$', task_change_team, name='helpdesk_task_change_team'),
    url(r'^task/change/team/$', task_detail_change_team, name='helpdesk_task_detail_change_team'),
    url(r'^task/change/priority/$', task_change_priority, name='helpdesk_task_change_priority'),
    url(r'^task/change/context/$', task_change_context, name='helpdesk_task_change_context'),
    url(r'^task/(?P<task_id>\d+)/attachment/add/$', attachment_add, name='helpdesk_task_attachment_add'),
    url(r'^task/(?P<task_id>\d+)/assign/$', task_assign, name='helpdesk_task_assign'),
    url(r'^task/(?P<task_id>\d+)/close/$', task_close, name='helpdesk_task_close'),
    url(r'^team/$', team, name='helpdesk_team'),
    url(r'^team/(?P<team_id>\d+)/edit/$', team, name='helpdesk_team_edit'),
    url(r'^context/$', context, name='helpdesk_context'),
    url(r'^context/(?P<context_id>\d+)/edit/$', context, name='helpdesk_context_edit'),
    url(r'^note/add/$', note_add, name='helpdesk_note_add'),
)


if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$',
         'django.views.static.serve',
         {'document_root': '/home/wiliam/devel/jabba/jabba/static'}),
    )

jabba/helpdesk/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _


class TaskManager(models.Manager):
    use_for_related_fields = True

    def open(self):
        return self.get_query_set().exclude(status=4)


def get_team_or_create():
    team, created = Team.objects.get_or_create(name=ugettext('Main'))
    return team


def get_context_or_create():
    context, created =  Context.objects.get_or_create(name=ugettext('Inbox'))
    return context


class Team(models.Model):
    name = models.CharField(_('Name'), max_length=128)

    def url_dashboard_team(self):
        return ('helpdesk_dashboard_team', [str(self.id)])
    url_dashboard_team = models.permalink(url_dashboard_team)

    def url_team_edit(self):
        return ('helpdesk_team_edit', [str(self.id)])
    url_team_edit = models.permalink(url_team_edit)

    def __unicode__(self):
        return self.name


class Task(models.Model):

    STATUS_CHOICES = (
        (1, _('Open')),
        (2, _('Reopened')),
        (4, _('Closed')),
    )

    PRIORITY_CHOICES = (
        (1, _('Critical')),
        (2, _('High')),
        (3, _('Normal')),
        (4, _('Low')),
    )

    description = models.TextField(_('Description'), blank=True, null=True,)
    context = models.ForeignKey('Context', verbose_name=_('Context'), default=get_context_or_create, related_name='tasks')
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    created_by = models.ForeignKey(User, verbose_name=_('Created by'), related_name='tasks_created')
    closed = models.DateTimeField(_('Closed'), blank=True, null=True)
    closed_by = models.ForeignKey(User, verbose_name=_('Closed by'), related_name='tasks_closed', blank=True, null=True)
    due = models.DateTimeField(_('Due date'), blank=True, null=True)
    show_from = models.DateTimeField(_('Show from'), blank=True, null=True)
    team = models.ForeignKey('Team', verbose_name=_('Team'), related_name='tasks', default=get_team_or_create)
    attachments = models.ManyToManyField('Attachment', verbose_name=_('Attachments'), blank=True, null=True)
    status = models.IntegerField(_('Status'), choices=STATUS_CHOICES, default=1)
    priority = models.IntegerField(_('Priority'), choices=PRIORITY_CHOICES, default=3, blank=3)
    assigned_to = models.ForeignKey(User, verbose_name=_('Assigned to'), related_name='tasks_assigned', blank=True, null=True)

    objects = TaskManager()

    def __unicode__(self):
        return self.description


class Context(models.Model):
    name = models.CharField(_('Name'), max_length=64)
    team = models.ForeignKey('Team', verbose_name=_('Team'), default=get_team_or_create, related_name='contexts')

    def url_context_edit(self):
        return ('helpdesk_context_edit', [str(self.id)])
    url_context_edit = models.permalink(url_context_edit)

    def __unicode__(self):
        return self.name


class Note(models.Model):
    created_by = models.ForeignKey(User, verbose_name=_('Created by'), related_name='notes_created')
    created_date = models.DateTimeField(_('Open date'), auto_now_add=True)
    description = models.TextField(_('Description'))
    task = models.ForeignKey('Task', verbose_name=_('Task'), related_name='notes')

    def __unicode__(self):
        return self.description


class Attachment(models.Model):
    file = models.FileField(_('File'), upload_to='attachment')
    filename = models.CharField(_('Filename'), max_length=128)
    mime_type = models.CharField(_('MIME Type'), max_length=32)
    size = models.IntegerField(_('Size'))

    def __unicode__(self):
        return self.filename

jabba/helpdesk/views.py
from datetime import datetime

from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.http import Http404, HttpResponseRedirect, HttpResponse, \
                        HttpResponseForbidden


from helpdesk.models import get_team_or_create,  get_context_or_create, Team, \
                            Task, Context
from helpdesk.forms import TeamForm, UserTaskForm, NoteForm, AttachmentForm, \
                           TeamTaskForm, ContextForm, PriorityForm, \
                           TeamChangeForm, ContextChangeForm



@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('helpdesk_dashboard_staff'))
    else:
        return HttpResponseRedirect(reverse('helpdesk_dashboard_user'))


@login_required
def dashboard_user(request):
    tasks = Task.objects.filter(created_by=request.user)
    open_tasks = tasks.filter(status=1).order_by('-created')
    closed_tasks = tasks.filter(status=4)
    return render_to_response(
        'helpdesk/dashboard_user.html',
        context_instance=RequestContext(
            request,
            {'user_task_form': UserTaskForm(),
             'open_tasks': open_tasks,
             'closed_tasks': closed_tasks,}
            )
        )


@login_required
def dashboard_staff(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    teams = Team.objects.exclude(name=get_team_or_create())
    new_tasks = Task.objects.filter(team=get_team_or_create())
    return render_to_response(
        'helpdesk/dashboard_staff.html',
        context_instance=RequestContext(
            request,
            {'new_tasks': new_tasks,
             'teams': teams,}
            )
        )


@login_required
def dashboard_team(request, team_id=0):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    team = get_object_or_404(Team, id=team_id)
    tasks_open = team.tasks.filter(status=1).filter(
        context=get_context_or_create()).order_by('-created')
    tasks_closed = team.tasks.filter(status=4)
    teamtaskform = TeamTaskForm(
        team, initial={'current_team':team.id, 'team':team.id})
    return render_to_response(
        'helpdesk/dashboard_team.html',
        context_instance=RequestContext(
            request,
            {'team': team,
             'tasks_open': tasks_open,
             'tasks_closed': tasks_closed,
             'teamtaskform': teamtaskform,}
            )
        )


@login_required
def task_detail(request, task_id=0):
    if task_id:
        task = get_object_or_404(Task, id=task_id)
        noteform = NoteForm(initial={'task':task_id})
        attachmentform = AttachmentForm(initial={'task':task_id})
        priorityform = PriorityForm(initial={'priority': task.priority, 'task': task_id})
        teamchangeform = TeamChangeForm(initial={'task':task_id, 'team': task.team.id})
        contextchangeform = ContextChangeForm(team=task.team, initial={'task':task_id, 'context': task.context.id})
    return render_to_response(
        'helpdesk/task_detail.html',
        {'task': task,
         'noteform': noteform,
         'attachmentform': attachmentform,
         'priorityform': priorityform,
         'teamchangeform': teamchangeform,
         'contextchangeform': contextchangeform,
        },
        context_instance=RequestContext(request)
        )


@login_required
def task_team_add(request):
    team = get_object_or_404(Team, id=request.POST['team'])
    form = TeamTaskForm(team)
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = TeamTaskForm(team, request.POST)
        if form.is_valid():
            task = form.save(request.user)
            return HttpResponseRedirect(
                reverse('helpdesk_dashboard_team',
                args=[request.POST['current_team']]))
    return render_to_response(
        'helpdesk/new.html',
        {'form': form,},
        context_instance=RequestContext(request)
        )


@login_required
def task_user_add(request, task_id=0):
    form = UserTaskForm()
    if request.method == 'POST':
        form = UserTaskForm(request.POST)
        if form.is_valid():
            task = form.save(request.user)
            return HttpResponseRedirect(
                reverse('helpdesk_dashboard_user'))
    return render_to_response(
        'helpdesk/new.html',
        {'form': form,},
        context_instance=RequestContext(request)
        )


@login_required
def task_change_team(request, task_id=0, team_id=0):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if task_id and team_id:
        task = get_object_or_404(Task, id=task_id)
        team = get_object_or_404(Team, id=team_id)
        task.team = team
        task.save()
        return HttpResponse('OK')
    else:
        return Http404


@login_required
def task_detail_change_team(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = TeamChangeForm(request.POST)
        if form.is_valid:
            task = get_object_or_404(Task, id=request.POST['task'])
            team = get_object_or_404(Team, id=request.POST['team'])
            task.team = team
            task.save()
    return HttpResponseRedirect(
        reverse('helpdesk_task_detail', args=[request.POST['task']])
        )


@login_required
def task_change_priority(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = PriorityForm(request.POST)
        if form.is_valid:
            task = get_object_or_404(Task, id=request.POST['task'])
            task.priority = request.POST['priority']
            task.save()
    return HttpResponseRedirect(
        reverse('helpdesk_task_detail', args=[request.POST['task']])
        )


@login_required
def task_assign(request, task_id):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if task_id:
        task = get_object_or_404(Task, id=task_id)
        task.assigned_to = request.user
        task.save()
        return HttpResponseRedirect(reverse('helpdesk_task_detail', args=[task_id]))



@login_required
def task_change_context(request):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = ContextForm(request.POST)
        if form.is_valid:
            task = get_object_or_404(Task, id=request.POST['task'])
            task.context = get_object_or_404(Context, id=request.POST['context'])
            task.save()
    return HttpResponseRedirect(
        reverse('helpdesk_task_detail', args=[request.POST['task']])
        )


@login_required
def task_close(request, task_id):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    if task_id:
        task = get_object_or_404(Task, id=task_id)
        task.closed = datetime.now()
        task.closed_by = request.user
        task.status = 4
        task.save()
        return HttpResponseRedirect(reverse('helpdesk_task_detail', args=[task_id]))


@login_required
def team(request, team_id=0):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    teams = Team.objects.all().exclude(name=get_team_or_create)
    form =  TeamForm()
    form_url = reverse('helpdesk_team')
    team = Team()
    if team_id:
        team = get_object_or_404(Team, id=team_id)
        form_url = team.url_team_edit()
        form = TeamForm(instance=team)
    if request.method == 'POST':
        form = TeamForm(request.POST, instance=team)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('helpdesk_team'))
    return render_to_response(
        'helpdesk/team.html',
        {'teams': teams,
         'teamform': form,
         'form_url': form_url,
        },
        context_instance=RequestContext(request)
        )


@login_required
def context(request, context_id=0):
    if not request.user.is_staff:
        return HttpResponseForbidden()
    contexts = Context.objects.all().exclude(name=get_context_or_create)
    form =  ContextForm()
    form_url = reverse('helpdesk_context')
    context = Context()
    if context_id:
        context = get_object_or_404(Context, id=context_id)
        form_url = context.url_context_edit()
        form = ContextForm(instance=context)
    if request.method == 'POST':
        form = ContextForm(request.POST, instance=context)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('helpdesk_context'))
    return render_to_response(
        'helpdesk/context.html',
        {'contexts': contexts,
         'contextform': form,
         'form_url': form_url,
        },
        context_instance=RequestContext(request)
        )


@login_required
def note_add(request):
    form = NoteForm()
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(
                reverse('helpdesk_task_detail',
                args=[request.POST['task']]))
    return render_to_response(
        'helpdesk/new.html',
        {'form': form,},
        context_instance=RequestContext(request)
        )


@login_required
def attachment_add(request, task_id):
    form = AttachmentForm(initial={'task':task_id})
    if request.method == 'POST':
        form = AttachmentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(
                reverse('helpdesk_task_detail',
                args=[request.POST['task']]))
    return render_to_response(

jabba/helpdesk/templates/helpdesk/base.html
{% extends "base_2col.html" %}
{% load i18n %}
{% block breadcrumb %}
  <a href="{% url helpdesk_dashboard_staff %}">{% trans "staff" %} ></a>
{% endblock %}
{% block menu %}
<ul>
  {% if user.is_staff %}
  <li><a href="{% url helpdesk_dashboard_staff %}">{% trans "Dashboard" %}</a></li>
  <li><a href="{% url helpdesk_team %}">{% trans "Team" %}</a></li>
  <li><a href="{% url helpdesk_context %}">{% trans "Context" %}</a></li>
  <li><a href="">{% trans "Statistics" %}</a></li>
  {% else %}
  <li><a href="{% url helpdesk_dashboard_user %}">{% trans "Dashboard" %}</a></li>
  {% endif %}
  </ul>
{% endblock %}

jabba/helpdesk/templates/helpdesk/context.html
{% extends "helpdesk/base.html" %}
{% load i18n %}
{% block left %}
<div class="container">
	<h2>{% trans "Contexts" %}</h2>
	{% if contexts %}
  <table cellspacing="0">
    <thead>
      <tr><th>{% trans "Context name" %}</th><th>{% trans "Team" %}</th></tr>
    </thead>
    <tbody>
    {% for c in contexts %}
    <tr class="{% cycle 'row1' 'row2' %}">
      <td><a href="{{ c.url_context_edit }}">{{ c.name }}</a></td>
      <td>{{ c.team }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
	{% else %}
	<div class="info">
	<p>{% trans "There are no context here at the moment." %}</p>
	</div>	
	{% endif %}
</div>
{% endblock %}
{% block rigth %}
    <div class="container">
      <h2>{% trans "New context" %}</h2>
      <form method="post" action="{{ form_url }}">{% csrf_token %}
      <ul>
        {{ contextform.as_ul }}
        <li>
          <input type="submit" value="{% trans "Submit"%}"/>
        </li>
      </ul>
      </form>
    </div>
{% endblock %}

jabba/helpdesk/templates/helpdesk/dashboard_staff.html
{% extends "helpdesk/base.html" %}
{% load i18n %}
{% block breadcrumb %}
  <strong>{% trans "staff" %}</strong>
{% endblock %}
{% block left %}
<div class="container">
	<h2>{% trans "Tasks" %}</h2>
	{% if new_tasks %}
	  <ul id="list">
    {% for t in new_tasks %}
    <li class="draggable">
      <span id="task_id">{{ t.id }}</span>
	    {{ t.description }}
    </li>
    {% endfor %}
    </ul>
	{% else %}
	<div class="info">
	<p>{% trans "There are no tasks here at the moment." %}</p>
	</div>	
	{% endif %}
</div>
{% endblock %}
{% block rigth %}
	{% if teams %}
	{% for team in teams %}
  <div class="container droppable">
    <h2><a href="{{ team.url_dashboard_team }}">{{ team.name }}</a></h2>
    <div class="teams">
      <ul>
        <li id="team_id">{{ team.id }}</li>
        <li id="task_count">{{ team.tasks.count }} Tasks</li>
        <li>{{ team.contexts.count }} Contexts</li>
      </ul>
    </div>
  </div>
  {% endfor %}
  {% else %}
  <div class="container">
  <h2>{% trans "Teams" %}</h2>
  <div class="info">
    <p>{% trans "There are no team here at the moment." %}</p>
    <p>{% trans "To add a team" %} <a href="{% url helpdesk_team %}">{% trans "click here" %}</a>.</p>
  </div>
  </div>
  {% endif %}
{% endblock %}

jabba/helpdesk/templates/helpdesk/dashboard_user.html
{% extends "helpdesk/base.html" %}
{% load i18n %}
{% block left %}
<div class="container">
	<h2>{% trans "Open tasks" %}</h2>
	{% if open_tasks %}
  <table cellspacing="0">
    <thead>
      <tr>
        <th>{% trans "Description" %}</th>
        <th>{% trans "Assigned to" %}</th>
        <th>{% trans "Created" %}</th>
      </tr>
    </thead>
    <tbody>
    {% for task in open_tasks %}
    <tr class="{% cycle 'row1' 'row2' %}">
      <td><a href="{% url helpdesk_task_detail task.id %}">{{ task.description }}</a></td>
      {% if task.assigned_to %}
      <td>{{ task.assigned_to }}</td>
      {% else %}
      <td>{% trans "Unassigned" %}</td>
      {% endif %}
      <td>{{ task.created|timesince }} {% trans "ago" %}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
	{% else %}
	<div class="info">
	  <p>{% trans "There are no open tasks here at the moment." %}</p>
	</div>	
	{% endif %}
</div> <!-- container -->
<div class="container">
	<h2>{% trans "Closed tasks" %}</h2>
	{% if closed_tasks %}
  <table cellspacing="0">
    <thead>
      <tr>
        <th>{% trans "Description" %}</th>
        <th>{% trans "Closed by" %}</th>
        <th>{% trans "Closed" %}</th>
      </tr>
    </thead>
    <tbody>
    {% for task in closed_tasks %}
    <tr class="{% cycle 'row1' 'row2' %}">
      <td>{{ task.description }}</td>
      <td>{{ task.closed_by }}</td>
      <td>{{ task.closed|timesince }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
	{% else %}
	<div class="info">
  	<p>{% trans "There are no closed tasks here at the moment." %}</p>
	</div>	
	{% endif %}
</div> <!-- container -->
{% endblock %}
{% block rigth %}
<div class="container">
  <h2>{% trans "New task" %}</h2>
  <form  method="post" action="{% url helpdesk_task_user_add %}">{% csrf_token %}
  <ul>
    {{ user_task_form.as_ul }}
    <li>
      <input type="submit" value="{% trans "Submit"%}"/>
    </li>
  </ul>
  </form>
</div> <!-- container -->
{% endblock %}

jabba/helpdesk/templates/helpdesk/new.html
{% extends "helpdesk/base.html" %}
{% load i18n %}
{% block content %}
<div class="add_form">
  <form enctype="multipart/form-data" method="post" action=".">{% csrf_token %}
    <ul>
      {{ form.as_ul }}
      <li>
        <input type="submit" value="{% trans "Submit"%}"/>
      </li>
    </ul>
  </form>
</div>
{% endblock %}

jabba/helpdesk/templates/helpdesk/task_detail.html
{% extends "helpdesk/base.html" %}
{% load i18n %}
{% block breadcrumb %}
  {{ block.super }}
  <a href="{% url helpdesk_dashboard_team task.team.id %}"> {{ task.team|lower }} > </a><strong>task</strong>
{% endblock %}
{% block left %}
<div class="container">
	<h2>{% trans "Task" %} ( {{ task.id }} ) {{ task.description|slice:":50" }}... </h2>
  <table cellspacing="0">
    <tbody>
    <tr>
      <th>{% trans "Created" %}</th>
      <td>{{ task.created_by }} {{ task.created|date:"D d M Y" }} ({{ task.created|timesince }} {% trans "ago" %})</td>
    </tr>
    <tr>
      <th>{% trans "Assigned to" %}</th>
      {% if task.assigned_to %}
        {% if user.is_staff %}
        <td>{{ task.assigned_to }} (<a href="{% url helpdesk_task_close task.id %}">{% trans "Close" %}</a>)</td>
        {% else %}
        <td>{{ task.assigned_to }}</td>
        {% endif %}
      {% else %}
        {% if user.is_staff %}
        <td>{% trans "Unassigned" %} (<a href="{% url helpdesk_task_assign task.id %}"> {% trans "Take" %} </a>)</td>
        {% else %}
        <td>{% trans "Unassigned" %}</td>
        {% endif %}
      {% endif %}
    </tr>
    <tr>
      <th>{% trans "Priority" %}</th>
      {% if user.is_staff %}
      <td>
      <div id="priority-form" title="{% trans "Select a priority"%}">
      <form method="post" action="{% url helpdesk_task_change_priority %}">{% csrf_token %}
      <ul>
        <li>
          {{ priorityform.as_ul }}
        </li>      
        <li>
          <input type="submit" value="{% trans "Change"%}"/>
        </li>
      </ul>
      </form>
      </div>
      {{ task.get_priority_display }} (<a id="change-priority" href="{% url helpdesk_task_change_priority %}"> {% trans "Change"%} </a>)
      </td>
      {% else %}
      <td>{{ task.get_priority_display }}</td>
      {% endif %}
    </tr>
    <tr>
      <th>{% trans "Team" %}</th>
      {% if user.is_staff %}
      <td>
      <div id="team-form" title="{% trans "Select a team"%}">
      <form method="post" action="{% url helpdesk_task_detail_change_team %}">{% csrf_token %}
      <ul>
        <li>
          {{ teamchangeform.as_ul }}
        </li>      
        <li>
          <input type="submit" value="{% trans "Change"%}"/>
        </li>
      </ul>
      </form>
      </div>
      {{ task.team }} (<a id="change-team" href="{% url helpdesk_task_detail_change_team %}"> {% trans "Change"%} </a>)
      </td>
      {% else %}
      <td>{{ task.team }}</td>
      {% endif %}
    </tr>
    <tr>
      <th>{% trans "Context" %}</th>
      {% if user.is_staff %}
      <td>
      <div id="context-form" title="{% trans "Select a context"%}">
      <form method="post" action="{% url helpdesk_task_change_context %}">{% csrf_token %}
      <ul>
        <li>
          {{ contextchangeform.as_ul }}
        </li>      
        <li>
          <input type="submit" value="{% trans "Change"%}"/>
        </li>
      </ul>
      </form>
      </div>
      {{ task.context }} (<a id="change-context" href="{% url helpdesk_task_change_context %}"> {% trans "Change"%} </a>)
      </td>
      {% else %}
      <td>{{ task.context }}</td>
      {% endif %}
    </tr>
    <tr>
      <th>{% trans "Attachments" %}</th>
      <td>
        (<a id="new-attachment" href="{% url helpdesk_task_attachment_add task.id %}"> {% trans "New"%} </a>)
        <div id="attachment-form" title="{% trans "Select an attachment"%}">
        <form enctype="multipart/form-data" method="post" action="{% url helpdesk_task_attachment_add task.id %}">{% csrf_token %}
        <ul>
          {{ attachmentform.as_ul }}
          <li>
            <input type="submit" value="{% trans "Submit"%}"/>
          </li>
        </ul>
        </form>
        </div>
      {% for a in task.attachments.all %}
        <a href="{{ a.file.url }}">{{ a.filename }} ({{ a.size|filesizeformat }}), </a>
      {% endfor %}
      </td>
    </tr>
    <tr>
      <th>{% trans "Description" %}</th>
      <td>{{ task.description }}</td>
    </tr>
    </tbody>
  </table>
</div>
<div class="container">
	<h2>{% trans "Notes" %}</h2>
	{% if task.notes.all %}
  <table cellspacing="0">
    <thead>
      <tr><th>{% trans "Description" %}</th><th>{% trans "Created by" %}</th><th>{% trans "Created" %}</th></tr>
    </thead>
    <tbody>
    {% for n in task.notes.all %}
    <tr class="{% cycle 'row1' 'row2' %}">
	    <td>{{ n.description }}</td><td>{{ n.created_by }}</td><td>{{ n.created_date|date:"d M Y" }}</td>
	  </tr>
    </div>
    {% endfor %}
    </tbody>
  </table>
	{% else %}
	<div class="info">
	<p>{% trans "There are no notes here at the moment." %}</p>
	</div>	
	{% endif %}
</div>
{% endblock %}
{% block rigth %}
<div class="container">
  <h2>{% trans "New note" %}</h2>
  <form method="post" action="{% url helpdesk_note_add %}">{% csrf_token %}
  <ul>
    {{ noteform.as_ul }}
    <li>
      <input type="submit" value="{% trans "Submit"%}"/>
    </li>
  </ul>
  </form>
</div>
{% endblock %}